# Generated by Django 4.0 on 2021-12-19 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('ren', 'Rent'), ('tra', 'Travel'), ('inv', 'Investment'), ('sho', 'Shopping'), ('lea', 'Learning'), ('fee', 'Fees'), ('oth', 'Other')], default='oth', max_length=3)),
                ('note', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
